name: bit-smtp-tunnel

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - --loglevel
      - info
      - --url
      - http://backend
    networks:
      - bit-smtp-network

networks:
  bit-smtp-network:
    external: true
    driver: bridge
